### PR TITLE
Create new base Flutter project

### PR DESCRIPTION
**Pull request by BrunoMartins11**
This PR deletes the old react mobile app and replaces it with a base Flutter project to begin new development.

### CODE REVIEW

**Review by nelsonmestevao — COMMENTED** [review]
Why don't you update the setup instructions now?

**Comment by hpereira98** [comment]
It seems ok to me.
The setup instructions can be a summarized version of the official Flutter documentation regarding this topic, but it is not a priority at the moment.

**Review by hpereira98 — DISMISSED** [review]

**Comment by BrunoMartins11** [comment]
@nelsonmestevao I will update this ASAP.

**Comment by herulume** [comment]
The file directory feels weird. From our "in-person" conversation you have told me the project needs to follow that file structure but other Flutter projects don't ([an example](https://github.com/FogosPT/fogosmobile)). That `native_moon` folder seems unnecessary and it brings two different README.

**Comment by BrunoMartins11** [comment]
If you don't want that folder there you have to change the name of this repo to *nativemoon* or *native_moon*.

**Comment by herulume** [comment]
Done.
Clean the extra folders/files when you have the time.
Good job.

**Review by hpereira98 — APPROVED** [review]
Seems good.

**Review by herulume — APPROVED** [review]

**Review by nelsonmestevao — APPROVED** [review]
:rocket:

**Pull request merged**
